services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DB_DSN=${DB_DSN}
      - RMQ_DSN=${RMQ_DSN}
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    environment:
      - DB_DSN=${DB_DSN}
    command: migrate -path=/root/migrations -database="${DB_DSN}" up
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: